{% set name = "django-guardian" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5ada52485c2deeb8247980cf8090f7375508df12ddb1644ac0f8ffb373a57164

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - pip
  run:
    - django-environ
    - guardian
    - python >={{ python_min }}
    - django >=3.2

test:
  imports:
    - guardian
  commands:
    - pip check
    - DJANGO_SETTINGS_MODULE=guardian.testapp.testsettings pytest --pyargs guardian
  requires:
    - django-environ >=0.12.0
    - pip
    - pytest >=8.3.4
    - pytest-django >=4.9.0
    - python {{ python_min }}

about:
  home: http://github.com/django-guardian/django-guardian
  summary: Per object permissions for Django
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - abraha2d
