{% set name = "django-guardian" %}
{% set version = "1.5.1" %}
{% set sha256 = "60a4932e322b4474ab76400f3f542ecdf9bee069dbed0ce0c7af55559ec83d3a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - django >=1.11
    - django-environ
    - bumpversion
    - mock

about:
  home: https://github.com/django-guardian/django-guardian
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Per object permissions for Django'
  description: |
    django-guardian is an implementation of per object permissions
    on top of Django's authorization backend
  doc_url: http://django-guardian.readthedocs.io/
  dev_url: https://github.com/django-guardian/django-guardian

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
