{% set name = "django-guardian" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0c79d55c4af2cfc14fbd19539846a1ebfed2a38198b7697e0f5177b7f654e1cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - django >=2.2
    - python >={{ python_min }}

test:
  commands:
    - pytest --pyargs guardian -c pytest.ini
  requires:
    - django-environ
    - mock
    - pytest
    - pytest-django
    - python {{ python_min }}
  source_files:
    - pytest.ini

about:
  home: http://github.com/django-guardian/django-guardian
  summary: Implementation of per object permissions for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - abraha2d
