{% set name = "django-guardian" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-guardian-{{ version }}.tar.gz
  sha256: c58a68ae76922d33e6bdc0e69af1892097838de56e93e78a8361090bcd9f89a0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - django >=2.2
    - python >={{ python_min }}

test:
  commands:
    - pytest --pyargs guardian -c pytest.ini
  requires:
    - django-environ
    - mock
    - pytest
    - pytest-django
    - python {{ python_min }}
  source_files:
    - pytest.ini

about:
  home: http://github.com/django-guardian/django-guardian
  summary: Implementation of per object permissions for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - abraha2d
